figure
subplot(2,2,1)
plot(w,abs(X))
title('X 的幅值')
ylabel('abs(X)')
xlabel('ω')
subplot(2,2,2)
plot(w,angle(X))
ylabel('angle(X)')
xlabel('ω')
title('X 的相角')
subplot(2,2,3)
plot(w,abs(Y))
title('Y 的幅值图')
subplot(2,2,4)
plot(w,angle(Y))
title('Y 的相角图')
