figure
subplot(2,2,1)
plot(w,abs(X))
title('e 题中 X 的幅值')
ylabel('abs(X)')
xlabel('ω')
subplot(2,2,2)
plot(w,angle(X))
ylabel('angle(X)')
xlabel('ω')
title('e 题中 X 的相角')
X1 = 1./(2+1j*w)+1./(2-1j*w);
subplot(2,2,3)
plot(w,abs(X1))
title('a 题中 X 的幅值')
ylabel('abs(X)')
xlabel('ω')
subplot(2,2,4)
plot(w,angle(X1))
title('a 题中 X 的相角')
ylabel('angle(X)')
xlabel('ω')
figure
subplot(1,2,1)
plot(w,abs(X))
title('e 题中 X 的幅值')
ylabel('abs(X)-e')
xlabel('ω')
ylim([0.001,1])
subplot(1,2,2)
plot(w,abs(X1))
title('a 题中 X 的幅值')
ylabel('abs(X)-a')
xlabel('ω')
xlim([-20,20])
ylim([0.001,1])
figure
semilogy(abs(X),abs(X1))
ylabel('abs(X)-e/a')
xlabel('ω')